version: '3'

services:
  backend1:
    build:
      context: https://github.com/XJCO2913/API_Backend.git#main
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

  backend_test1:
    build:
      context: https://github.com/XJCO2913/API_Backend.git#develop
      dockerfile: Dockerfile
    ports:
      - 8099:8080
    depends_on:
      mysql:
        condition: service_healthy


          # backend_micro_gateway:
    # build:
      # context: https://github.com/XJCO2913/API_Backend.git#lab/microservice
        # dockerfile: Dockerfile
        # ports:
      # - 8081:8080
        #  depends_on:
      # mysql:
        # condition: service_healthy


          # backend_auth:
          # build:
          # context: https://github.com/XJCO2913/API_Backend.git#lab/microservice
          #  dockerfile: Dockerfile.auth
          # ports:
          #  - 8888:8888
          # depends_on:
          # mysql:
          # condition: service_healthy


  user_frontend:
    build:
      context: https://github.com/XJCO2913/Web_Frontend.git#develop
      dockerfile: Dockerfile
    ports:
      - 5173:80
    volumes:
      - /home/lighthouse/Web_Frontend/nginx.conf:/etc/nginx/conf.d/default.conf

        # user_map:
    # build:
      # context: https://github.com/XJCO2913/Web_Frontend.git#feature/map
        # dockerfile: Dockerfile
        # ports:
      # - 5555:80
        # volumes:
      #    - /home/lighthouse/Web_Frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  admin_frontend:
    build:
      context: https://github.com/XJCO2913/Management_Frontend.git#develop
      dockerfile: Dockerfile
    ports:
      - 5174:80
    volumes:
      - /home/lighthouse/Web_Frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: 'mysql:latest'
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=API_XJCO2913_TEST
      - MYSQL_USER=xiaofei
      - MYSQL_PASSWORD=2021110003
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass 2021110003
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "5000:5000"  
    volumes:
      - /home/lighthouse/xjco2913/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/lighthouse/xjco2913/log:/var/log/nginx:rw


  prometheus:
    image: prom/prometheus:latest
    restart: always
    user: root
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./data/prometheus_data:/prometheus"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3001:3000"

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    restart: always

  minio:
    image: quay.io/minio/minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 2021110003
    command: server /data --console-address ":9001"
